### ISSUE TITLE
Failed to insert 1 movie in Trakt

### ISSUE THREAD

**Issue by doomlerd** [StegSchreck/RatS#102]
**Describe the bug**
While exporting from Movielens to Trakt, a movie is always failed (137/138), and the ...Trakt-failed.json contains all the transfers, not just the one that failed.

**To Reproduce**
1. Try to transfer from Movielens to Trakt

**Expected behavior**
138/138 exports or at least the json to contain a name of the specific movie that failed.

**Desktop (please complete the following information):**
- Version:  889072a
- Platform OS:  Windows 10
- Firefox version:  71.0 (64-bit)
- Geckodriver version:  0.26.0
- Python version:  3.8.0
- PIP version:  19.2.3
- Running in a virtualenv?:  no
- Running in Docker?:  no
- Executed command:  `python transfer_ratings.py --source movielens --destination trakt -x`

## Stacktrace
```
===== [95m[1mMovielens[0m: CSV downloaded to dir/20191229183428_Movielens.csv
===== getting movies from CSV

===== [95m[1mMovielens[0m: saved 138 parsed movies to dir/20191229183428_Movielens.json
===== [95m[1mTrakt[0m: posting 138 movies
100% (138 of 138) |##############################################################| Elapsed Time: 0:34:40 Time:  0:34:40

===== [95m[1mTrakt[0m: sucessfully posted 137 of 138 movies
===== [95m[1mTrakt[0m: export data for 1 failed movies to dir/20191229183427_Trakt_failed.json
```

## Geckodriver log
none

**Additional context**
I had to run it with -x because it can't be headless ( no xvfb on windows )

movielens : 
![image](https://user-images.githubusercontent.com/26717942/71561821-0ec00d00-2a7c-11ea-8de6-b0d0e45ef2de.png)
trakt after the transfer : 
![image](https://user-images.githubusercontent.com/26717942/71561835-38793400-2a7c-11ea-8afc-aea00ba365f6.png)

**Comment by StegSchreck** [comment]
Hey @doomlerd.
Thank you for bringing this to my attention. The bug is fixed now and the script will only save the movies to the failed-movies-file, which actually failed. You can also see which movie failed during the run, by enabling the verbose option, using the `-v` parameter. 
It can sometimes happen, that the movie cannot be found at the destination. Most of the time this relates to very niche movies or to localization.
