### ISSUE TITLE
How to execute on windows

### ISSUE THREAD

**Issue by dracount** [StegSchreck/RatS#105]
**Describe the bug**
I have tried following the directions but I am getting an error running on windows 10. I have followed the wiki.

**To Reproduce**
1. download and unzip repository
2. install requirements.txt
3. execute the script

**Expected behavior**
no error

**Desktop (please complete the following information):**
- Version: Release v0.12.1
- Platform OS: Windows 10
- Firefox version: 72.0.1
- Geckodriver version: 
- Python version: 3.7.3
- PIP version: 19.3.1
- Running in a virtualenv?: no
- Running in Docker?: no
- Executed command: python transfer_ratings.py --source trakt --destination imdb -x

## Stacktrace
```
Traceback (most recent call last):
  File "transfer_ratings.py", line 13, in <module>
    from RatS.criticker.criticker_ratings_inserter import CritickerRatingsInserter
  File "D:\media server\lists\RatS-master\RatS\criticker\criticker_ratings_inserter.py", line 8, in <module>
    from RatS.criticker.criticker_site import Criticker
  File "D:\media server\lists\RatS-master\RatS\criticker\criticker_site.py", line 1, in <module>
    from RatS.base.base_site import Site
  File "D:\media server\lists\RatS-master\RatS\base\base_site.py", line 12, in <module>
    from RatS.utils.browser_handler import BrowserHandler
  File "D:\media server\lists\RatS-master\RatS\utils\browser_handler.py", line 8, in <module>
    from xvfbwrapper import Xvfb
  File "C:\Users\David Sevel\AppData\Local\Programs\Python\Python37-32\lib\site-packages\xvfbwrapper.py", line 15, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```

## Geckodriver log
```
windows 
```

**Additional context**
Followed directions on wiki

**Comment by StegSchreck** [comment]
Hey @dracount.
Thank you for notifying me about the problems on your platform. Sadly, Docker on Windows still works a little bit differently as on a Linux/Unix environment. Currently, I can not support or debug Windows environments (as I don't a windows machine myself). This is also stated in the Readme. There is already an open issue for making dockerized RatS work on Windows --> #19. Therefore, I will close this ticket.

**Comment by wisdomtooth** [comment]
[This](https://stackoverflow.com/a/25471508/553579) workaround (seemingly) worked for me, but I got bogged down at [another issue](https://github.com/StegSchreck/RatS/issues/187).
