### ISSUE TITLE
Docker seems to be missing parsers

### ISSUE THREAD

**Issue by MattiasStorm** [StegSchreck/RatS#193]
**Describe the bug**
Docker port doesn't have all parsers.

**To Reproduce**
1. Install the docker version: `docker pull stegschreck/rats`
2. Try to run the command as supplied: `docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source Filmtipset --destination IMDB`
3. Get error message:
```
ERROR: No parser matching 'Filmtipset' found.

===== ABORTING =====
Available parsers:
 - CRITICKER
 - FILMAFFINITY
 - ICHECKMOVIES
 - IMDB
 - LETTERBOXD
 - LISTAL
 - MOVIELENS
 - MOVIEPILOT
 - PLEX
 - ROTTENTOMATOES
 - TMDB
 - TRAKT
```
**Expected behavior**
Expected the docker to be up to date and include all parsers.

**Desktop (please complete the following information):**
- Version: 0.13
- Platform OS:  Ubuntu 22.04 LTS
- Firefox version: Docker version
- Geckodriver version: Docker version
- Python version: Docker version
- PIP version: Docker version
- Running in a virtualenv?: Docker
- Running in Docker?: Yes
- Executed command: `docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg stegschreck/rats python3 transfer_ratings.py --source Filmtipset --destination IMDB`

**Comment by StegSchreck** [comment]
As automated builds are not available on the free plan of Docker hub anymore, the `latest` was not up to date.
please use the image from the GitHub registry instead.

```sh
docker pull ghcr.io/stegschreck/rats/rats:latest
```
