### ISSUE TITLE
Docker Image

### ISSUE THREAD

**Issue by BuSHari** [StegSchreck/RatS#2]
Hi,

Thank you for that tool!
It will be great if you can create a docker image for that tool, so i can use it in my NAS.

**Comment by StegSchreck** [comment]
Hey. Thank you for your feedback!
There is a docker container now! :) https://hub.docker.com/r/stegschreck/rats/
I adjusted the readme accordingly.
I hope you'll enjoy it. If you have any more improvement ideas or find any bugs, feel free to write another ticket.

Best regards
