### ISSUE TITLE
Trakt: invalid literal for int() with base 10

### ISSUE THREAD

**Issue by lead0r** [StegSchreck/RatS#218]
[20221113143918_IMDB.csv](https://github.com/StegSchreck/RatS/files/9997515/20221113143918_IMDB.csv)
**Describe the bug**
Invalid literal when importing imdb ratings to trakt. Similar to https://github.com/StegSchreck/RatS/issues/141

To be honest, I don't know which movie is meant with the search term in the error message. Hence, I don't know which is the invalid literal. I have Boyhood, Oldboy and Oh Boy in my list, but I also don't know how RatS works under the hood.

**To Reproduce**
I have a modified version of the docker image, based on this comment: https://github.com/StegSchreck/RatS/issues/43#issuecomment-1102699727

that's why my docker image has a different name

**Expected behavior**
Successfull import of imdb ratings to trakt

**Desktop (please complete the following information):**
- Platform OS: macOS
- Running in Docker?: yes
- Executed command: docker run -it -v ~/.RatS.cfg:/RatS/RatS/credentials.cfg rats-fixed-new python3 transfer_ratings.py --source imdb --destination trakt

## Stacktrace
```
===== IMDB: CSV downloaded to /RatS/RatS/exports/20221107140037_IMDB.csv
===== getting movies from CSV

===== IMDB: saved 115 parsed movies to /RatS/RatS/exports/20221107140037_IMDB.json
===== Trakt: posting 115 movies
 38% (44 of 115) |#################################################################################                                                                                                                                    | Elapsed Time: 0:11:31 ETA:   0:18:41
ERROR: There was an exception inside Trakt (see below). Skipping insertion.
Traceback (most recent call last):
  File "transfer_ratings.py", line 267, in insert_movie_ratings
    inserter.insert(movies, source)
  File "/RatS/RatS/base/base_ratings_inserter.py", line 49, in insert
    movie_details_page_found = self._go_to_movie_details_page(movie)
  File "/RatS/RatS/base/base_ratings_inserter.py", line 101, in _go_to_movie_details_page
    success = self._find_movie(movie)
  File "/RatS/RatS/base/base_ratings_inserter.py", line 123, in _find_movie
    return self._is_movie_in_search_results(movie, search_results)
  File "/RatS/RatS/base/base_ratings_inserter.py", line 127, in _is_movie_in_search_results
    if self._is_requested_movie(movie, search_result):
  File "/RatS/RatS/trakt/trakt_ratings_inserter.py", line 31, in _is_requested_movie
    return self._check_movie_details(movie, search_result)
  File "/RatS/RatS/trakt/trakt_ratings_inserter.py", line 42, in _check_movie_details
    return self._compare_external_links(
  File "/RatS/RatS/trakt/trakt_ratings_inserter.py", line 69, in _compare_external_links
    ) == IMDB.normalize_imdb_id(link["href"].split("/")[-1])
  File "/RatS/RatS/imdb/imdb_site.py", line 49, in normalize_imdb_id
    return int(imdb_id.replace("tt", ""))
ValueError: invalid literal for int() with base 10: 'find?q=Boy+Oh+Boy&s='

===== ABORTING =====
```

Edit: Attached my imdb.csv
Edit: Attached the  correct .csv

**Comment by StegSchreck** [comment]
Hey @lead0r.
Looking at the imdb.csv you posted, there is defintely something gone wrong: 
- The csv-header line appears again in the line 118 (which it shouldn't)
- Lines 56 and 57 are completely broken.

As this file is just a download from IMDB, the error might be on their side. Have you tried to run the script more than once? If yes, is this error reproducable for you?

**Comment by lead0r** [comment]
Hey @StegSchreck 
Yes, I always get the same error

**Comment by StegSchreck** [comment]
After having another look today, I have now understood the issue. RatS is trying to find the movie "Oh Boy" on Trakt, where it comes across [this search result](https://trakt.tv/movies/boy-oh-boy-2021), which does not have an IMDB id connected to it. In the past, Trakt just didn't display the IMDB link in these cases, so this wasn't an issue in the past.
I have adapted the script accordingly to ingore these cases now.
