### ISSUE TITLE
error transfer_ratings.py

### ISSUE THREAD

**Issue by 5u4573** [StegSchreck/RatS#33]
**hello, when I execute the command "python3 transfer_ratings.py --source trakt --destination movielens" it returns the following error without the possibility of continuing**

File "transfer_ratings.py", line 8, in <module>
    from RatS.criticker.criticker_ratings_inserter import CritickerRatingsInserter
  File "/home/user/RatS/RatS/criticker/criticker_ratings_inserter.py", line 4, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named 'bs4'

**Comment by StegSchreck** [comment]
Hey.
Thanks for your message.
Did you install the dependencies for RatS before executing the script?
’pip install -r requirements.txt’

**Comment by 5u4573** [comment]
yes, the dependencies were installed before
(pip install -r requirements.txt)

today I tried again executing the dependency installation command first and then the script obtaining the same result previously written

**Comment by StegSchreck** [comment]
Alright. That's odd then. It seems that the dependency is not installed correctly at first glance. Could you please provide the following informations?
* waht is your operating system and its version?
* is your os running inside a vm or container?
* are you using a virtual environment for installing the dependencies (and running the script)?
* output of `python --version`
* output of `pip --version`
* output of `pip install -r requirements.txt`
* output of `pip freeze --local` (before and after installing the dependencies)

Thank you.

**Comment by 5u4573** [comment]
what is your operating system and its version?
Ubuntu 16.04 AMD64

    is your os running inside a vm or container?
Hyper-V

    are you using a virtual environment for installing the dependencies (and running the script)?
no

    output of python --version
Python 2.7.12

output of python3 --version
Python 3.5.2


    output of pip --version
pip 9.0.1 from /home/user/.local/lib/python2.7/site-packages (python 2.7)


    output of pip install -r requirements.txt
Requirement already satisfied: beautifulsoup4 in /home/user/.local/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: selenium in /home/user/.local/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: configparser in /home/user/.local/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: xvfbwrapper in /home/user/.local/lib/python2.7/site-packages (from -r requirements.txt (line 4))


    output of pip freeze --local (before and after installing the dependencies)
adium-theme-ubuntu==0.3.4
beautifulsoup4==4.6.0
configparser==3.5.0
selenium==3.8.0
unity-lens-photos==1.0
xvfbwrapper==0.2.9

**Comment by StegSchreck** [comment]
Thanks for the informations. Can you try to install the dependencies via `pip3` instead of `pip`?
