### ISSUE TITLE
How to use on a headless server?

### ISSUE THREAD

**Issue by pitylee** [StegSchreck/RatS#36]
I want this so badly, and it is awesome, but how can one use it on a headless no gui server environment where nor xvfb nor xorg is installed?

**Comment by StegSchreck** [comment]
Thanks for your feedback. Unfortunately, for some of the sites the script does need the (hidden) Firefox for interacting with the dynamically altered DOM. That's the reason I had to switch from PhantomJS to Geckodriver/Firefox at some point. To be honest, I don't have a solution for your use-case right now. But I will have a look at this later. If you find a solution or workaround before me, I would appreciate if you post it here.
Can you use this on an environment with a running x-server for now?

**Comment by mason-xx** [comment]
Would love to see a solution too since I only have a headless server available and would love to automate that there.

**Comment by StegSchreck** [comment]
Hey, thanks for stating your interest. 
Has anyone actually already tried executing this project on a headless server? I'm asking, because as far as I read so far, it should already work, as Xvfb is part of the requirements installed by pip during the setup. Thus a headless server doesn't need to have it already. It just needs python (or docker if you want to use the provided image). But I have to admit that I didn't try this for myself yet as I have currently no headless server at hand to play around with.

**Comment by mason-xx** [comment]
Yep, i tried that but it throws the following

`
Traceback (most recent call last):
  File "transfer_ratings.py", line 149, in <module>
    main()
  File "transfer_ratings.py", line 65, in main
    execute(args)
  File "transfer_ratings.py", line 110, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/opt/RatS/RatS/trakt/trakt_ratings_parser.py", line 9, in __init__
    super(TraktRatingsParser, self).__init__(Trakt(args), args)
  File "/opt/RatS/RatS/trakt/trakt_site.py", line 11, in __init__
    super(Trakt, self).__init__(args)
  File "/opt/RatS/RatS/base/base_site.py", line 33, in __init__
    self._init_browser()
  File "/opt/RatS/RatS/base/base_site.py", line 54, in _init_browser
    self.display = Xvfb()
  File "/usr/local/lib/python3.6/dist-packages/xvfbwrapper.py", line 41, in __init__
    raise EnvironmentError(msg)
OSError: Can not find Xvfb. Please install it and try again.
`

**Comment by StegSchreck** [comment]
Regarding the Trakt API: The problem was that it wouldn't work, if your user profile is set to private. The way I implemented it will work for any user, independently from the visibility of the profile.

**Comment by StegSchreck** [comment]
Regarding Xvfb: You're right, I only defined the wrapper in my requirements, not the Xvfb itself. But I'm glad you could simply install it via `apt`. Thus, I will close the ticket now.
