### ISSUE TITLE
Use standard progress bar

### ISSUE THREAD

**Issue by StegSchreck** [StegSchreck/RatS#38]
in order to reduce project's complexity, just use an existing solution for displaying the progress, ETA etc.

possible alternatives:
* https://progressbar-2.readthedocs.io/en/latest/
* https://pypi.python.org/pypi/tqdm

*UAC*
* visual representation of progress (the actual progress bar)
* percentage finished so far
* ETA to finish
* (optional) processed items / total items
* (optional) time taken so far

**Comment by s-surineni** [comment]
Can I have a go at this?

**Comment by StegSchreck** [comment]
@s-surineni 

sure, go ahead :)
