### ISSUE TITLE
Implement version check on startup

### ISSUE THREAD

**Issue by StegSchreck** [StegSchreck/RatS#39]
* check the latest release under https://github.com/StegSchreck/RatS/releases/latest
* notify user via WARN log

**Comment by StegSchreck** [comment]
Hey. Sure, glad to have some help.
I was thinking about a file in the repository which will be written by Travis when a tag is pushed and the build is successful.

**Comment by anurag-rai** [comment]
Ok, so maybe we can add small bash commands in `after_script` of `travis.yml` that creates/appends to a file some version tag. But where will this version tag come from in the first place?

**Comment by StegSchreck** [comment]
for the backwards compatibility I would suggest to assume the local copy is outdated, when no version file is present.
