### ISSUE TITLE
Adjust the filename of the data parsed

### ISSUE THREAD

**Issue by robot2xl** [StegSchreck/RatS#4]
You say: "You can use the data you parsed before again without parsing again. The parser tells you in which file he saved his results, the folder is ./RatS/exports. You can use this data by commenting out the parsing in the transfer_ratings.py script and comment in the file loader part, where you just have to adjust the filename."

To make use of a json saved file I understand the text should be like this:

def execute(args):
    # PARSING DATA
    #parser = get_parser_from_arg(args.source)(args)
    #movies = parse_data_from_source(parser)
    # FILE LOADING
     movies = load_data_from_file(filename)
    # POSTING THE DATA
    inserter = get_inserter_from_arg(args.destination)(args)
    insert_movie_ratings(inserter, movies, type(parser.site).__name__)

My question is, where in the text should I put the file name?

My file is called: 20170809172059_Criticker.json

Hopefully you can tell me where in the text. 

Thank you.

**Comment by StegSchreck** [comment]
You are right, it is not very convenient to use this "feature" right now (it was originally introduced only for debugging purposes). I will provide a more convenient way of usage, probably this evening.

**Comment by StegSchreck** [comment]
I did some changes.
You can use an existing file by calling `python3 transfer_ratings.py --source trakt --destination movielens --file 20170721191143_Trakt.json` without the need of changing any sourcecode anymore.

I hope this helps you.

**Comment by robot2xl** [comment]
Thanks! 👍

**Comment by robot2xl** [comment]
One more thing... do you think you could include https://www.icheckmovies.com ?

I wish you could

😋

**Comment by StegSchreck** [comment]
I will put it on my roadmap. You can see it here: #5

**Comment by robot2xl** [comment]
Thanks! 👍
