### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by sugarman402** [StegSchreck/RatS#40]
Hi. Just installed everything as wrote in the README. When i run the command i get the error written above.

## System
* Version: Latest commit ed9f288 
* Platform: Ubuntu 16.04.3 LTS
* Firefox version: 58.0 (x86)
* Python version: 3.5.2
* PIP version: 9.0.1
* Running in a virtualenv?: no
* Executed command: `python3 /opt/RatS/transfer_ratings.py --source trakt --destination imdb` 

## Stacktrace
```
:~$ python3 /opt/RatS/transfer_ratings.py --source trakt --destination imdb
Traceback (most recent call last):
  File "/opt/RatS/transfer_ratings.py", line 158, in <module>
    main()
  File "/opt/RatS/transfer_ratings.py", line 65, in main
    execute(args)
  File "/opt/RatS/transfer_ratings.py", line 110, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/opt/RatS/RatS/trakt/trakt_ratings_parser.py", line 9, in __init__
    super(TraktRatingsParser, self).__init__(Trakt(args), args)
  File "/opt/RatS/RatS/trakt/trakt_site.py", line 11, in __init__
    super(Trakt, self).__init__(args)
  File "/opt/RatS/RatS/base/base_site.py", line 35, in __init__
    self._init_browser()
  File "/opt/RatS/RatS/base/base_site.py", line 84, in _init_browser
    log_path="{timestamp}_geckodriver.log".format(timestamp=TIMESTAMP)
  File "/home/sugar/.local/lib/python3.5/site-packages/selenium/webdriver/firefox/webdriver.py", line 148, in __init__
    self.service.start()
  File "/home/sugar/.local/lib/python3.5/site-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error
```

## Geckodriver log

0 byte, empty geckodriver logfiles created as the error occures.

**Comment by StegSchreck** [comment]
Hey @sugarman402. Thank you for your input. Unfortunately, I couldn't reproduce the described behaviour on CentOS7 or Manjaro Arch Linux. I therefore did the following:
* Started a Docker container with Ubuntu 16.04: `docker run -it ubuntu:16.04 bash`
* Installed everything which I need from apt:  `apt-get install sudo git firefox curl get xvfb python3 python3-pip vim`
* Get the repo: `git clone https://github.com/StegSchreck/RatS.git && cd RatS`
* Install the Python dependencies: `pip3 install -r requirements.txt`
* Install Geckodriver (as it is not available from apt): `sudo ./InstallGeckodriver.sh`
* Create and fill the credentials file: `vim RatS/credentials.cfg`
* Run the script: `python3 transfer_ratings.py -s trakt -d imdb`

![image](https://user-images.githubusercontent.com/9078002/35463880-418be428-02f3-11e8-95da-00c6454eca5e.png)

This also worked for me, as you can see. So I therefore am sorry not to be able to see the same error you got. Am I missing something?

Could you try to use the Docker solution from this repository? I hope this will not have the same issue.

**Comment by sugarman402** [comment]
Thank you so much. It seems the error came from my ubuntu's enviromental issues(another python scripts throwed the same error) , i don't really know what was the problem, yesterday i reinstalled the whole os. Anyway from docker ubuntu it replied with the same excpetions.
I tried from windows docker and it worked like a charm. So it sorks fine, thank you.

**Comment by StegSchreck** [comment]
Glad to hear :) Thanks for the update.
