### ISSUE TITLE
Handle captcha challenge in IMDB login

### ISSUE THREAD

**Issue by StegSchreck** [StegSchreck/RatS#43]
During the login to IMDB, it might happen, that a captcha is required. 
* Research what causes this 
  * maybe something in the login url?
* Enable user to enter this captcha in order to continue normal processing

**Comment by hairyhippy** [comment]
+1

I am getting this Captcha issue.  See my comments on this issue thread:
https://github.com/StegSchreck/RatS/issues/19

**Comment by StegSchreck** [comment]
Yeah, the captcha is a thing that is very hard to bypass just from the code. (As it is intended to)
Haven't figured out yet what conditions trigger it on IMDB side.

**Comment by hairyhippy** [comment]
I tried running the script again today and still getting the Captcha issue.  Is there a workaround, like clearing cookies, etc?

**Comment by hairyhippy** [comment]
Sadly still getting the Captcha issue.  Is it worth me re-pulling the latest code?

**Comment by StegSchreck** [comment]
I did not have time to invest here unfortunately. As mentioned before, Captchas are very much designed for this purpose. You could try to run the script once with the `-x` option, so that the Firefox browser is visible to you and when the login screen comes up with the captcha, solve it manually. IIRC, doing this resolved the issue for me permanently.

**Comment by hairyhippy** [comment]
so the script would be "python3 transfer_ratings.py --source trakt --destination imdb -x"?

**Comment by StegSchreck** [comment]
> so the script would be "python3 transfer_ratings.py --source trakt --destination imdb -x"?

exactly :)

**Comment by hairyhippy** [comment]
I get the following when running the script with the "-x" at the end:
Traceback (most recent call last):
  File "transfer_ratings.py", line 234, in <module>
    main()
  File "transfer_ratings.py", line 86, in main
    execute(args)
  File "transfer_ratings.py", line 134, in execute
    parser = get_parser_from_arg(args.source)(args)
  File "/home/hairyhippy/RatS/RatS/trakt/trakt_ratings_parser.py", line 9, in __init__
    super(TraktRatingsParser, self).__init__(Trakt(args), args)
  File "/home/hairyhippy/RatS/RatS/trakt/trakt_site.py", line 12, in __init__
    super(Trakt, self).__init__(args)
  File "/home/hairyhippy/RatS/RatS/base/base_site.py", line 36, in __init__
    self._init_browser()
  File "/home/hairyhippy/RatS/RatS/base/base_site.py", line 67, in _init_browser
    self.browser_handler = BrowserHandler(self.args)
  File "/home/hairyhippy/RatS/RatS/utils/browser_handler.py", line 26, in __init__
    self.browser = Firefox(
  File "/home/hairyhippy/.local/lib/python3.8/site-packages/selenium/webdriver/firefox/webdriver.py", line 170, in __init__
    RemoteWebDriver.__init__(
  File "/home/hairyhippy/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/hairyhippy/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/hairyhippy/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/hairyhippy/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Process unexpectedly closed with status 1

**Comment by hairyhippy** [comment]
So it seems that exception is to do with needing to use Firefox in headless mode.  If anyone knows how to simply solve that it would be great as the code on a website I found isn't working. 

I am very very new to Linux FYI...

**Comment by hairyhippy** [comment]
Ok, I am getting closer!  I ended up uninstalling Ubuntu and reinstalling and connecting via a remote desktop connection.  When I run the script now, Firefox opens for each and every film rated on Trakt (in a single window) but when it gets to IMDB, it opens and I see the Captcha but before I can enter it, Firefox closes and the script aborts.  Is there a way to stop Firefox from closing and giving me a chance to enter the Captcha?

**Comment by StegSchreck** [comment]
I was thinking to login in Firefox separately, before running the script.

**Comment by hairyhippy** [comment]
I did that, sadly didn't work.  When I logged into imdb it didn't ask me to complete the captcha.

Excuse my nativity but can the code be changed that if it asks for a captcha that the script is paused until the user completes the captcha and then presses enter to resume the script?

I did try myself, sort of, by changing the time.sleep to 60 (seconds) in the imdb_site.py file but that didn't work either.

I'll continue to have a play around to see if I can somehow get this to work :-)

**Comment by hairyhippy** [comment]
Woohoo!

I got it to work.  I changed time.sleep to 15 in base_site.py and was able to log into imdb with Captcha!

Although the script did stop when updating the ratings in IMDB as there was a movie that didn't have a star rating.  If that happens the code should just skip that movie and move on...

That said what it did highlight is there were some movies that were rating in my Trakt that I actually hadn't watched, etc and therefore I was able to clean that up as well.

Thanks Steg for putting this together.  Whilst it took my an age to get it to work it was worth it!

**Comment by paxamit** [comment]
For me, increasing sleep to 3, stopped IMDB from showing captcha at all. 
I think this is some form of boot protection (sleep < 3 will always give me captcha)

**Comment by lead0r** [comment]
Increasing sleep has worked for me for a while, but now I always get a captcha error, regardless of which value I choose for time.sleep

**Comment by lead0r** [comment]
I 'solved' this by running RatS manually instead of the Docker image and then I was able to solve the captcha myself by increasing time.sleep

**Comment by StegSchreck** [comment]
will become obsolete with #306
