### ISSUE TITLE
www.icheckmovies.com ratings parser

### ISSUE THREAD

**Issue by StegSchreck** [StegSchreck/RatS#5]
Implement ratings parser for https://www.icheckmovies.com.
requested by @robot2xl

**Comment by StegSchreck** [comment]
@robot2xl, can I ask you a questions about this? icheckmovies does only save whether you like or dislike the movie. all other sites I implemented so far have a 10 step rating system. What are your thoughts on this? How should a :+1: or :-1: be translated to a 10 points system?

**Comment by robot2xl** [comment]
IMDB ratings can be imported into the "checked" list. https://www.icheckmovies.com/import/imdbvotes/

**Comment by StegSchreck** [comment]
Yeah, that's for inserting data from other sources (e.g. Trakt or IMDB) into iCheckMovies. That's what the ticket #10 is about.
My question in this ticket concerns the other way around.

**Comment by robot2xl** [comment]
👍 = 8
👎  = 4

**Comment by StegSchreck** [comment]
alright, thanks. I will make this configurable, just in case someone wants to change it. I did the same for the iCheckMovies Inserter.
