### ISSUE TITLE
Unknown Bug?

### ISSUE THREAD

**Issue by okabak123** [StegSchreck/RatS#64]
First of all, thanks for this little script. 

This may or may not be a bug. I might be doing something wrong here. Here is the log:

> [root@osoxes RatS]# python3 transfer_ratings.py --source letterboxd --destination criticker
> ===== Letterboxd: CSV downloaded to /root/RatS/RatS/exports/20181016093134_Letterboxd.csv
> ===== getting movies from CSV
> 
> ===== Letterboxd: saved 1286 parsed movies to /root/RatS/RatS/exports/20181016093134_Letterboxd.json
> ===== Criticker: posting 1286 movies                   
> Traceback (most recent call last):
>   File "/root/RatS/RatS/criticker/criticker_ratings_inserter.py", line 59, in _post_movie_rating
>     score = self.site.browser.find_element_by_id('fi_scoring_div').find_element_by_class_name('rating')
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 398, in find_element_by_class_name
>     return self.find_element(by=By.CLASS_NAME, value=name)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 659, in find_element
>     {"using": by, "value": value})['value']
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webelement.py", line 633, in _execute
>     return self._parent.execute(command, params)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: .rating
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "transfer_ratings.py", line 168, in <module>
>     main()
>   File "transfer_ratings.py", line 65, in main
>     execute(args)
>   File "transfer_ratings.py", line 112, in execute
>     execute_inserting(args, movies, parser)
>   File "transfer_ratings.py", line 123, in execute_inserting
>     insert_movie_ratings(inserter, movies, type(parser.site).__name__)
>   File "transfer_ratings.py", line 164, in insert_movie_ratings
>     inserter.insert(movies, source)
>   File "/root/RatS/RatS/base/base_ratings_inserter.py", line 41, in insert
>     self._post_movie_rating(movie[source.lower()]['my_rating'])
>   File "/root/RatS/RatS/criticker/criticker_ratings_inserter.py", line 64, in _post_movie_rating
>     self._insert_rating(converted_rating)
>   File "/root/RatS/RatS/criticker/criticker_ratings_inserter.py", line 67, in _insert_rating
>     score_input = self.site.browser.find_element_by_xpath("//input[@class='scorebox_input']")
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 394, in find_element_by_xpath
>     return self.find_element(by=By.XPATH, value=xpath)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/lib/python3.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: //input[@class='scorebox_input']

**Desktop:**
- Version: v0.11.4
- Platform OS: Arch Linux 2018.09
- Firefox version: 62.0
- Geckdrover version: 0.21.0
- Python version: 3.7.0
- PIP version: 18.0
- Running in a virtualenv?: yes
- Running in Docker?: no
- Executed command: python3 transfer_ratings.py --source letterboxd -destination criticker

**Comment by StegSchreck** [comment]
Hey @okabak123.
Thank you very much for reporting this issue. In fact, I could reproduce the described behavior and adjusted the xpath used to find the scoring form on the criticker page. 

Best regards!
