### ISSUE TITLE
Rotten Tomatoes Parser 

### ISSUE THREAD

**Issue by studgeek** [StegSchreck/RatS#73]
A Parser for Rotten Tomatoes. 

If someone finds time to work on this, they can find a Rotten Tomatoes scraper here for letterboxd which should hopefully be a good start.
https://www.reddit.com/r/Letterboxd/comments/57917e/import_rotten_tomatoes_ratings_to_letterboxd/

**Comment by StegSchreck** [comment]
The [linked script](https://greasyfork.org/en/scripts/23947-rotten-tomatoes-export-csv-button/code) has a totally different approach than this project. But the detection of the fields to parse on Rotten Tomatoes might be of reference.
