### ISSUE TITLE
Error Timeout loading page after 300000ms

### ISSUE THREAD

**Issue by memnos** [StegSchreck/RatS#95]
Hello,
after this command i have this:

python3 transfer_ratings.py --source trakt --destination tmdb --destination imdb

> ===== Trakt: Parsing 9 pages with 536 movies in total
>  10% (57 of 536) |#                | Elapsed Time: 0:09:20 ETA:   5:59:41Traceback (most recent call last):
>   File "transfer_ratings.py", line 180, in <module>
>     main()
>   File "transfer_ratings.py", line 77, in main
>     execute(args)
>   File "transfer_ratings.py", line 123, in execute
>     movies = execute_parsing(args, parser)
>   File "transfer_ratings.py", line 145, in execute_parsing
>     movies = parse_data_from_source(parser)
>   File "transfer_ratings.py", line 150, in parse_data_from_source
>     movies = parser.parse()
>   File "/opt/RatS/RatS/base/base_ratings_parser.py", line 31, in parse
>     self._parse_ratings()
>   File "/opt/RatS/RatS/base/base_ratings_parser.py", line 73, in _parse_ratings
>     self._parse_movie_listing_page(movie_listing_page)
>   File "/opt/RatS/RatS/base/base_ratings_parser.py", line 94, in _parse_movie_listing_page
>     movie = self._parse_movie_tile(movie_tile)
>   File "/opt/RatS/RatS/base/base_ratings_parser.py", line 142, in _parse_movie_tile
>     self._go_to_movie_details_page(movie)
>   File "/opt/RatS/RatS/base/base_ratings_parser.py", line 160, in _go_to_movie_details_page
>     self.site.browser.get(movie[self.site.site_name.lower()]['url'])
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 333, in get
>     self.execute(Command.GET, {'url': url})
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.TimeoutException: Message: Timeout loading page after 300000ms
> 

Is there anything i can do?

**Comment by StegSchreck** [comment]
Hey @memnos. 
In my experience this can happen with a slow internet connection sometimes. 
Have you tried to run the script again or does it fail every time?

**Comment by memnos** [comment]
Yes, i run it 7 times, 
My internet connecton is about 90 Mb/sec down and 20 up.

**Comment by StegSchreck** [comment]
Alright, so that's most probably not the issue. Does it always fail at the same entry? 
If yes, you might try to use the `-x` parameter to have the browser visible and try to see what happens actually. Alternatively, you could use the `-vvv` parameter to have a more verbose console output

**Comment by memnos** [comment]
I don't think it is always at the same time.
Here are what i had the last try:
15% (85 of 536) |##########                                                        | Elapsed Time: 0:12:14 ETA:   0:36:52^

42% (227 of 536) |###########################                                      | Elapsed Time: 0:14:23 ETA:   1:11:34T

Once i remember it stopped at 7 of 536

**Comment by memnos** [comment]
It seems that for same reason it stops parsing.
This time it stops at n°16.
It went for fast till there then stops and got the error:

===== Trakt: [16/536] parsed {'title': 'Extremely Wicked, Shockingly Evil and Vile', 'trakt': {'id': '303985', 'url': 'https://trakt.tv/movies/extremely-wicked-shockingly-evil-and-vile-2019', 'my_rating': 8}, 'year': 2019, 'imdb': {'url': 'http://www.imdb.com/title/tt2481498', 'id': 'tt2481498'}, 'tmdb': {'url': 'https://www.themoviedb.org/movie/457799', 'id': '457799'}}

Traceback (most recent call last):
  File "transfer_ratings.py", line 180, in <module>
    main()
  File "transfer_ratings.py", line 77, in main
    execute(args)
  File "transfer_ratings.py", line 123, in execute
    movies = execute_parsing(args, parser)
  File "transfer_ratings.py", line 145, in execute_parsing
    movies = parse_data_from_source(parser)
  File "transfer_ratings.py", line 150, in parse_data_from_source
    movies = parser.parse()
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 31, in parse
    self._parse_ratings()
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 73, in _parse_ratings
    self._parse_movie_listing_page(movie_listing_page)
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 94, in _parse_movie_listing_page
    movie = self._parse_movie_tile(movie_tile)
  File "/opt/RatS/RatS/base/base_ratings_parser.py", line 149, in _parse_movie_tile
    self.parse_movie_details_page(movie)
  File "/opt/RatS/RatS/trakt/trakt_ratings_parser.py", line 45, in parse_movie_details_page
    movie_details_page = BeautifulSoup(self.site.browser.page_source, 'html.parser')
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 679, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

**Comment by memnos** [comment]
Now i'm not having the timeout error anymore, so maybe it was really an internet problem.
But i always have the error of the previous post, always for a diffent movie.

What does this message mean?

selenium.common.exceptions.WebDriverException: Message: Failed to decode response from marionette

**Comment by StegSchreck** [comment]
From my experience the exception comes up if the connection between the Firefox browser (via geckodriver) and Selenium is interrupted, e.g. by killing the browser.

**Comment by memnos** [comment]
So, is there anything i can do?

**Comment by StegSchreck** [comment]
I can only reproduce the error, if I kill firefox by force.
The only thing coming to my mind right now, is check if Firefox and Geckodriver are up to date (see the readme). If the update does not help, I suggest to try the Docker container.

May I ask how much RAM and CPU power the machine has that you use? Have you had a look on the numbers (e.g. via `glances` or `htop`)?

**Comment by memnos** [comment]
cat /proc/cpuinfo

> processor       : 0
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 63
> model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
> stepping        : 2
> microcode       : 0x1
> cpu MHz         : 2399.996
> cache size      : 16384 KB
> physical id     : 0
> siblings        : 2
> core id         : 0
> cpu cores       : 2
> apicid          : 0
> initial apicid  : 0
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 13
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb kaiser fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
> bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
> bogomips        : 4799.99
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 40 bits physical, 48 bits virtual
> power management:
> 
> processor       : 1
> vendor_id       : GenuineIntel
> cpu family      : 6
> model           : 63
> model name      : Intel(R) Xeon(R) CPU E5-2620 v3 @ 2.40GHz
> stepping        : 2
> microcode       : 0x1
> cpu MHz         : 2399.996
> cache size      : 16384 KB
> physical id     : 0
> siblings        : 2
> core id         : 1
> cpu cores       : 2
> apicid          : 1
> initial apicid  : 1
> fpu             : yes
> fpu_exception   : yes
> cpuid level     : 13
> wp              : yes
> flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss ht syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon rep_good nopl xtopology tsc_known_freq pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm invpcid_single ssbd ibrs ibpb kaiser fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid xsaveopt arat
> bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs
> bogomips        : 4799.99
> clflush size    : 64
> cache_alignment : 64
> address sizes   : 40 bits physical, 48 bits virtual
> power management:

 cat /proc/meminfo

> MemTotal:        6110576 kB
> MemFree:          170364 kB
> MemAvailable:     792064 kB
> Buffers:           54344 kB
> Cached:           901780 kB
> SwapCached:            0 kB
> Active:          4635640 kB
> Inactive:         745396 kB
> Active(anon):    4425944 kB
> Inactive(anon):   140572 kB
> Active(file):     209696 kB
> Inactive(file):   604824 kB
> Unevictable:           8 kB
> Mlocked:               8 kB
> SwapTotal:             0 kB
> SwapFree:              0 kB
> Dirty:                88 kB
> Writeback:             0 kB
> AnonPages:       4425020 kB
> Mapped:           206952 kB
> Shmem:            141508 kB
> Slab:              84588 kB
> SReclaimable:      41108 kB
> SUnreclaim:        43480 kB
> KernelStack:       14080 kB
> PageTables:        50092 kB
> NFS_Unstable:          0 kB
> Bounce:                0 kB
> WritebackTmp:          0 kB
> CommitLimit:     3055288 kB
> Committed_AS:    8304028 kB
> VmallocTotal:   34359738367 kB
> VmallocUsed:           0 kB
> VmallocChunk:          0 kB
> HardwareCorrupted:     0 kB
> AnonHugePages:     22528 kB
> CmaTotal:              0 kB
> CmaFree:               0 kB
> HugePages_Total:       0
> HugePages_Free:        0
> HugePages_Rsvd:        0
> HugePages_Surp:        0
> Hugepagesize:       2048 kB
> DirectMap4k:      192368 kB
> DirectMap2M:     6098944 kB
> DirectMap1G:     2097152 kB
>

**Comment by memnos** [comment]
Sorry, how can i check if geckodriver is up to date?
I installed it with ./InstallGeckodriver.sh`

geckodriver --version

> geckodriver 0.26.0 (e9783a644016 2019-10-10 13:38 +0000)
> 
> The source code of this program is available from
> testing/geckodriver in https://hg.mozilla.org/mozilla-central.
> 
> This program is subject to the terms of the Mozilla Public License 2.0.
> You can obtain a copy of the license at https://mozilla.org/MPL/2.0/.
> 

firefox --version

> Mozilla Firefox 69.0.2

**Comment by StegSchreck** [comment]
Have you keeping an eye on the resource consumption while running the script?
My assumption is that the browser does not answer back to selenium in time because it has fewer resources available.

**Comment by memnos** [comment]
The resouces are near 100% often.

I tried to run in docker and i had much better results.

Trakt import finished ok
Tmdb export finished ok
I had error in imdb export

Here what i had:

> ===== Trakt: Parsing 10 pages with 543 movies in total
> 100% (543 of 543) |######################| Elapsed Time: 0:49:23 Time:  0:49:23
> 
> ===== Trakt: saved 543 parsed movies to /RatS/RatS/exports/20191019144302_Trakt.json
> ===== TMDB: posting 543 movies
> ===== saving movies to CSV
> 
> ===== TMDB: The file with 543 movies was uploaded and will be process by the servers. You may check your TMDB account later.
> Note, that this might not overwrite any existing ratings.
> ===== IMDB: posting 543 movies
>  35% (192 of 543) |#######               | Elapsed Time: 0:19:42 ETA:   2:08:49Traceback (most recent call last):
>   File "transfer_ratings.py", line 176, in <module>
>     main()
>   File "transfer_ratings.py", line 73, in main
>     execute(args)
>   File "transfer_ratings.py", line 120, in execute
>     execute_inserting(args, movies, parser)
>   File "transfer_ratings.py", line 131, in execute_inserting
>     insert_movie_ratings(inserter, movies, type(parser.site).__name__)
>   File "transfer_ratings.py", line 172, in insert_movie_ratings
>     inserter.insert(movies, source)
>   File "/RatS/RatS/base/base_ratings_inserter.py", line 44, in insert
>     self._post_movie_rating(movie[source.lower()]['my_rating'])
>   File "/RatS/RatS/base/base_ratings_inserter.py", line 146, in _post_movie_rating
>     raise e
>   File "/RatS/RatS/base/base_ratings_inserter.py", line 141, in _post_movie_rating
>     self._click_rating(my_rating)
>   File "/RatS/RatS/imdb/imdb_ratings_inserter.py", line 43, in _click_rating
>     ratings_button = self.site.browser.find_element_by_class_name('star-rating-button')\
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 564, in find_element_by_class_name
>     return self.find_element(by=By.CLASS_NAME, value=name)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 978, in find_element
>     'value': value})['value']
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
>     self.error_handler.check_response(response)
>   File "/usr/local/lib/python3.6/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
>     raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.InvalidSessionIdException: Message: Tried to run command without establishing a connection
>

**Comment by StegSchreck** [comment]
That kinda confirms my assumption, that the browser is too slow answering back to selenium if the resources are insufficient.

But nice that it worked using Docker :)

The InvalidSessionIdException is a new one to be honest. I have to look into that.

**Comment by memnos** [comment]
Also with a second try i had the same error tring to export to imdb.

BTW, is there a way not to make import al the times from track, but save import in a file and use it to export to source?

**Comment by StegSchreck** [comment]
Sure. Every successful run saves a files to your local hard disk (the name of the file is printed after the parsing). If the insertion fails, you can use that file for a re-run using the `-f` parameter. You can find more on that in the Readme.
